### ISSUE TITLE
in getDatasetFields, a decimal10_3 field in a thor file is being retrieve & shown as a REAL field

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/HPCC-JAPIs#39]
Example: dashboard cluster, https://216.19.105.2:18010/#/stub/Files-DL/LogicalFiles-DL/mythorxxbirtxxcustomers-DL/Source

**Comment by rpastrana** [comment]
https://track.hpccsystems.com/browse/JAPI-6
