### ISSUE TITLE
Now that wsAttributesClient() is being initialized from the wsClient(), the attributesPort is incorrect

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/HPCC-JAPIs#62]
wsAttributes services reside on the 8145 port (or 18145, if the protocol is https).

When getPlatform().getHPCCWSClient().getWsAttributesClient() is called, the attributesClient is initialized with the connection object designed for wsClient, that has port 8010 specified.

**Comment by rpastrana** [comment]
https://github.com/hpcc-systems/HPCC-JAPIs/pull/64
