### ISSUE TITLE
FetchRawResults failing for archived workunit logical filenames

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/HPCC-JAPIs#67]
When calling  WUResultResponse result = wsWorkunits.fetchRawResults("W20140320-064321", 0, "mythor", true, 0, 50);, if Workunit "W20140320-064321" is archived, this returns nothing.

the WUResult object also allows a logical filename to be sent in as an input parameter. When this is used instead of workunit ID, the data is returned correctly.

Options: 
Replace workunit with logical filename as a parameter to fetchRawResults
add logical filename as an optional parameter to fetchRawResults
add fetchRawResultsByLogicalname function.

Your preference?

**Comment by rpastrana** [comment]
what do you think about this fix? https://github.com/hpcc-systems/HPCC-JAPIs/pull/68
