### ISSUE TITLE
Compile errors with Java 1.8 jre

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/HPCC-JAPIs#83]
I noticed that in the DataSingleton class, there’s an @Override indicator on the run() method. This is causing a compile error with my eclipse jre (1.8). Since it’s not actually overriding anything. Can this be fixed? Same issue with Version.compareTo()—it’s implementing the compareTo() interface, not overriding a base class method.

**Comment by rpastrana** [comment]
@GordonSmith just heads-up this will most likely affect the eclipse plugin code as well...
