### ISSUE TITLE
Wrap getWsWorkunitsServiceSoap().WUResult() to avoid throwing error when workunit is archived

### ISSUE THREAD

**Issue by drealeed** [hpcc-systems/HPCC-JAPIs#88]
Create a wrapper method in HPCCWsWorkunitsClient, getWuResult(WUResult params), that calls
    getSoapProxy().getWsWorkunitsServiceSoap().WUResult(params);

It should check if the workunit is archived, and if it is, call WUAction with ActionType restore for the workunit before getting the result.

Needed to fix DSP Issue

**Comment by rpastrana** [comment]
moving all bugs to jira:
https://track.hpccsystems.com/browse/JAPI-9
