### ISSUE TITLE
Set jobname using HPCCWsClient.submitECLandGetResults()

### ISSUE THREAD

**Issue by dhanasiddharth** [hpcc-systems/HPCC-JAPIs#93]
Jobname is set through `WorkunitInfo.setJobname()` and `WorkunitInfo` object is passed to `HPCCWsClient.submitECLandGetResults()` to execute, but JAPI runs the workunit without setting Jobname.

Can you add in this feature?

**Comment by rpastrana** [comment]
Thanks for this submission @dhanasiddharth. Please take a look at this change:
https://github.com/hpcc-systems/HPCC-JAPIs/pull/94
It is available in hpcc-systems:WSClient-V0.6 and should resolve this issue.

**Comment by rpastrana** [comment]
@dhanasiddharth please let me know if that change fixed the issue so we can close this report, thanks.

**Comment by dhanasiddharth** [comment]
@rpastrana this fix is working for me. thanks.

**Comment by rpastrana** [comment]
Great to hear! Let me know if you find anything else.
